name:                hask-csproj
version:             0.1.0.0
github:              "vlad2048/hask-csproj"
license:             BSD3
author:              "Vlad Niculescu"
maintainer:          "vlad.nic@gmail.com"
copyright:           "Vlad Niculescu"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vlad2048/hask-csproj#readme>

dependencies:
- base >= 4.7 && < 5
- xml
- containers
- directory
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-top-binds
- -Wno-unused-imports
- -Wno-missing-export-lists
# - -XNamedFieldPuns

default-extensions:
  NamedFieldPuns

library:
  source-dirs: src

executables:
  hask-csproj-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-csproj

tests:
  hask-csproj-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-csproj
